// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaF4qfPl2tMvBZjULy4XkfInIXt-fXp-M',
    appId: '1:206072794651:web:fed25cf3316aba05fa32be',
    messagingSenderId: '206072794651',
    projectId: 'amafoundation-6f2f1',
    authDomain: 'amafoundation-6f2f1.firebaseapp.com',
    storageBucket: 'amafoundation-6f2f1.appspot.com',
    measurementId: 'G-F96LM22MMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmZAmA4Lpc5EkiEK1khELIk5Xw3ScKRd8',
    appId: '1:206072794651:android:7dfc156470fe63e8fa32be',
    messagingSenderId: '206072794651',
    projectId: 'amafoundation-6f2f1',
    storageBucket: 'amafoundation-6f2f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ2bhfApMsKqO2UjW0KD-pAf6kyks20uY',
    appId: '1:206072794651:ios:16476190f63a3867fa32be',
    messagingSenderId: '206072794651',
    projectId: 'amafoundation-6f2f1',
    storageBucket: 'amafoundation-6f2f1.appspot.com',
    androidClientId: '206072794651-nbaa2kova2aqdfmkmd0qta78opulka92.apps.googleusercontent.com',
    iosClientId: '206072794651-9gcac1df43pm6dgo7hr6jb01nfvu448h.apps.googleusercontent.com',
    iosBundleId: 'com.example.amaeyeclinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ2bhfApMsKqO2UjW0KD-pAf6kyks20uY',
    appId: '1:206072794651:ios:8c7fe3e78ea842eafa32be',
    messagingSenderId: '206072794651',
    projectId: 'amafoundation-6f2f1',
    storageBucket: 'amafoundation-6f2f1.appspot.com',
    androidClientId: '206072794651-nbaa2kova2aqdfmkmd0qta78opulka92.apps.googleusercontent.com',
    iosClientId: '206072794651-t63fkc9c5n7ku297om32jtd719uh75ed.apps.googleusercontent.com',
    iosBundleId: 'com.example.amaeyeclinic.RunnerTests',
  );
}
